### ISSUE TITLE
Segmentation fault when starting server with CUDA support

### ISSUE THREAD

**Issue by jaycase1** [abetlen/llama-cpp-python#406] opened 2023-06-20 13:40 UTC
Prerequisites

clone the repo update submodules and buils, then try to start the server liek:
CUDA_VISIBLE_DEVICES=0 python3 -m llama_cpp.server --model /home/ec2-user/SageMaker/quant_models/gpt4-x-vicuna-13B.ggmlv3.q4_0.bin --n_gpu_layers 43

Expected Behavior

server start, no errors.

Error:
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA A10G
llama.cpp: loading model from /home/ec2-user/SageMaker/quant_models/gpt4-x-vicuna-13B.ggmlv3.q4_0.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32001
llama_model_load_internal: n_ctx      = 512
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =    0.09 MB
llama_model_load_internal: using CUDA for GPU acceleration
llama_model_load_internal: mem required  = 9031.71 MB (+ 1608.00 MB per state)
llama_model_load_internal: offloading 0 repeating layers to GPU
llama_model_load_internal: offloaded 0/43 layers to GPU
llama_model_load_internal: total VRAM used: 43 MB
Segmentation fault

And I want to know how to solve the segmentation fault error?

Thanks!!!

**Comment by gjmulder** [comment] 2023-06-20 14:04
You're going to need to provide a lot more details as per the issue template. 

e.g. Linux or Windows? Version of CUDA? Version of llama-cpp-python? Output of `nvidia-smi`.

**Comment by jaycase1** [comment] 2023-06-20 14:53
run code on Linux platform and The output of Nvidia smi is shown in the following figure:
![image](https://github.com/abetlen/llama-cpp-python/assets/45376697/c94b1f76-bbf7-4200-9042-5b5c50d6c86b)

mvcc --version is 
![image](https://github.com/abetlen/llama-cpp-python/assets/45376697/5ca09216-f03c-45b6-9605-5bccda8ac45e)

**Comment by gjmulder** [comment] 2023-06-20 19:48
While this may not be the cause of your segmentation fault, your `nvidia-smi` reports CUDA version 12.0. `nvcc --version` reports version 11.8.

Try removing all your CUDA installs and nvidia driver and install 12.1 with the latest nvidia 5.30 driver. Then recompile the package.

If you're still getting the segmentation fault, I'd try to install the latest [llama.cpp](https://github.com/ggerganov/llama.cpp), as a segmentation fault is more likely to be caused by the `llama.cpp` library than Python.

**Comment by gjmulder** [comment] 2023-07-10 06:55
Closing. Please reopen if the problem is reproducible with the latest `llama-cpp-python` which includes an updated `llama.cpp`

**Closed by gjmulder** 2023-07-10 06:55 UTC
Labels: build, llama.cpp
