### ISSUE TITLE
Can't build 0.1.64 with cuBLAS support. Can build 0.1.63 in the same environment. 

### ISSUE THREAD

**Issue by Barafu** [abetlen/llama-cpp-python#403] opened 2023-06-20 04:27 UTC
I am using Oobabooga on Windows 11, all the latest updates. 

python-llama-cpp 0.1.64 works fine on CPU. 0.1.63 builds just fine with cuBLAS support too. However, building 0.1.64 with cuBLAS fails with a long log. 

I also need to add `-DCMAKE_CUDA_ARCHITECTURES=native` to the `CMAKE_ARGS` or it does not build, complaining that it is missing. 0.1.63 did not require that too. 

[Here is normal log.](https://pastebin.com/uW5bYeGn)
[Here is verbose log](https://pastebin.com/H67m15We)

**Comment by berkut1** [comment] 2023-06-20 05:32
With `set "CUDAFLAGS=-arch=all -lcublas"` it builds with no problem.

**Comment by noneabove1182** [comment] 2023-06-20 18:40
I'm having a problem with this too on linux, was working in the past but now for some reason i'm getting swamped with these errors:

CMake Error in vendor/llama.cpp/CMakeLists.txt:
CUDA_ARCHITECTURES is set to "native", but no GPU was detected.

this is during a docker build, so there is no GPU.. but it worked before

**Comment by abetlen** [comment] 2023-06-20 18:52
But otherwise llama.cpp builds correctly as a standalone program with the same flags?

**Comment by gjmulder** [comment] 2023-07-10 06:55
Closing. Please reopen if the problem is reproducible with the latest `llama-cpp-python` which includes an updated `llama.cpp`

**Closed by gjmulder** 2023-07-10 06:55 UTC
Labels: build, windows, oobabooga
