### ISSUE TITLE
ValueError: Model path does not exist

### ISSUE THREAD

**Issue by valdesguefa** [abetlen/llama-cpp-python#226] opened 2023-05-17 18:07 UTC
Please i need help. I have this issue when i try to run vicuna-13b model.
root@DESKTOP-EEQG16M:/mnt/f/AI_and_data/LLAMA_models# python3 test_LLama_cpp.py
Traceback (most recent call last):
  File "test_LLama_cpp.py", line 2, in <module>
    llm = Llama(
  File "/usr/local/lib/python3.8/dist-packages/llama_cpp/llama.py", line 155, in __init__
    raise ValueError(f"Model path does not exist: {model_path}")
ValueError: Model path does not exist: F:\AI_and_data\LLAMA_models\llama.cpp\models\ggml-vicuna-13b-4bit.bin
Exception ignored in: <function Llama.__del__ at 0x7f1db5ea4b80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/llama_cpp/llama.py", line 1076, in __del__
    if self.ctx is not None:
AttributeError: 'Llama' object has no attribute 'ctx'

**Comment by gjmulder** [comment] 2023-05-17 18:08
`Model path does not exist: F:\AI_and_data\LLAMA_models\llama.cpp\models\ggml-vicuna-13b-4bit.bin`

That looks like a Windows path but you seem to be on Linux?

**Comment by valdesguefa** [comment] 2023-05-17 18:51
i use WSL

**Comment by Celppu** [comment] 2023-05-17 22:40
In wsl you need to use the path where windows file system is mounted. For example "/mnt/c/Users/..." to access the model in windows file system

**Comment by valdesguefa** [comment] 2023-05-17 23:36
I use relative path

**Comment by gjmulder** [comment] 2023-05-18 02:53
And?

**Comment by valdesguefa** [comment] 2023-05-18 16:22
I have thé sale issue

**Comment by gjmulder** [comment] 2023-05-23 10:10
Can you review #225, please?

**Comment by gjmulder** [comment] 2023-06-02 13:57
Closing. Reopen if the issue is not resolved.

**Closed by gjmulder** 2023-06-02 13:57 UTC
Labels: duplicate, invalid, question, windows

**Comment by asmaemou** [comment] 2024-04-13 11:48
I have this issue can you help me solve it:
raise ValueError(f"Model path does not exist: {model_path}")

**Comment by Kkhatter-Deloitte** [comment] 2024-04-25 09:41
Can someone please share the fix for this?

File "/Users/**userame**/PycharmProjects/PythonAdventure/.venv/lib/python3.11/site-packages/llama_cpp/llama.py", line 320, in __init__
    raise ValueError(f"Model path does not exist: {model_path}")
ValueError: Model path does not exist: **/Users/userame/.ollama/models/llama3:latest**
