### ISSUE TITLE
COMMAND-R Compatibility

### ISSUE THREAD

**Issue by Nachotellez72** [abetlen/llama-cpp-python#1291] opened 2024-03-19 23:57 UTC
Is there a timeline for COMMAND-R integration?

**Comment by JuanRossi2000** [comment] 2024-03-19 23:58
Llama cpp already has it. Hope this gets updated soon :/

**Comment by abetlen** [comment] 2024-03-20 16:46
Closing as duplicate of #1279

**Closed by abetlen** 2024-03-20 16:46 UTC
Labels: duplicate
