### ISSUE TITLE
"Illegal instruction" when trying to run the server using a precompiled docker image

### ISSUE THREAD

**Issue by vmajor** [abetlen/llama-cpp-python#272] opened 2023-05-25 11:08 UTC
# Expected Behavior

I am trying to execute this:

`docker run --rm -it -p 8000:8000 -v /home/xxxx/models:/models -e MODEL=/models/gpt4-alpaca-lora_mlp-65B/gpt4-alpaca-lora_mlp-65B.ggmlv3.q5_1.bin ghcr.io/abetlen/llama-cpp-python:latest`

and I expect the model to load and server to start. I am using the model quantized by The Bloke according to the current latest specs of llama.ccp ggml implementation

# Current Behavior

```
llama.cpp: loading model from /models/gpt4-alpaca-lora_mlp-65B/gpt4-alpaca-lora_mlp-65B.ggmlv3.q5_1.bin
Illegal instruction
```

# Environment and Context

Linux DESKTOP-xxx 5.15.68.1-microsoft-standard-WSL2+ #2 SMP

```
$ python3 3.10.9
$ make GNU Make 4.3
$ g++ (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
```

# Steps to Reproduce

Please provide detailed steps for reproducing the issue. We are not sitting in front of your screen, so the more detail the better.

`docker run --rm -it -p 8000:8000 -v /home/xxxx/models:/models -e MODEL=/models/gpt4-alpaca-lora_mlp-65B/gpt4-alpaca-lora_mlp-65B.ggmlv3.q5_1.bin ghcr.io/abetlen/llama-cpp-python:latest`

**Comment by gjmulder** [comment] 2023-05-25 11:10
MLP models aren't supported by `llama.cpp` AFAIK

**Comment by vmajor** [comment] 2023-05-25 11:12
Wow fast reply. I am using alpaca-lora-65B.ggml.q5_1.bin with llama-cpp-python directly inside a python app and it works well. I tried to load this model using the docker server path and it gave me the same error: "Illegal instruction"

So the incompatibility is not with llama.cpp

**Comment by vmajor** [comment] 2023-05-25 11:29
The standalone server is running well, so the error has something to do with either the docker image or what it is trying to do and what my environment (WSL2) is letting it do:

```
gpt4-alpaca-lora_mlp-65B/gpt4-alpaca-lora_mlp-65B.ggmlv3.q5_1.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 8192
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 64
llama_model_load_internal: n_layer    = 80
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 9 (mostly Q5_1)
llama_model_load_internal: n_ff       = 22016
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 65B
llama_model_load_internal: ggml ctx size =    0.18 MB
llama_model_load_internal: mem required  = 50284.21 MB (+ 5120.00 MB per state)
warning: failed to mlock 196608000-byte buffer (after previously locking 0 bytes): Cannot allocate memory
Try increasing RLIMIT_MLOCK ('ulimit -l' as root).
....................................................................................................
llama_init_from_file: kv self size  = 5120.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
INFO:     Started server process [2244388]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
```

**Comment by gjmulder** [comment] 2023-05-25 12:02
On further thought "illegal instruction" could be due to the fact that the Docker image was compiled on another computer that supports vector instructions not supported on your current hardware. Did you build the Docker image locally?

**Comment by gjmulder** [comment] 2023-05-25 12:43
Entirely likely then.

There's sample Dockerfiles in the root dir, or I just created a pull request #270 that needs some smoke testing, if you have the time :wink:

**Comment by chen369** [comment] 2023-05-27 16:59
Im getting this issues as well. 
I have manually built 'llama-cpp-python'  and it fails similarly `Illegal instruction (core dumped)` as soon as you load `from llama_cpp import Llama`

Has anyone else have this issue to ? 
Im on Almalinux 9 with python 3.11

**Comment by gjmulder** [comment] 2023-05-27 18:42
> I have manually built 'llama-cpp-python'

On the same hardware without any virtualisation?

**Comment by chen369** [comment] 2023-05-28 00:36
> > I have manually built 'llama-cpp-python'
> 
> On the same hardware without any virtualisation?

Yes, Im using virtualization, Im using a Dell R820 with Proxmox 7. 
I have a VM running Almalinux 9

What the point is, Im having a `Illegal instruction (core dumped)` errors everytime im trying to use "
llama-cpp-python" However, If I used llama-cpp directly I have no issues. Its only when I use this python binding with cuBLAS being built. `CMAKE_ARGS="-DLLAMA_CUBLAS=on -CMAKE_CUDA_ARCHITECTURES=native" FORCE_CMAKE=1 pip install llama-cpp-python  --no-cache-dir` or even manually building it from source. 

I have no idea what logs to even collect, I checked `journalctl` and found nothing of intrest other than 
```
May 27 15:29:46 localhost.localdomain kernel: traps: python3.9[84283] trap invalid opcode ip:7f3cec006c2a sp:7ffdbd2a9920 error:0 in libllama.so[7f3cebff2000+45000]
May 27 15:29:46 localhost.localdomain systemd[1]: Started Process Core Dump (PID 84284/UID 0).
May 27 15:29:47 localhost.localdomain systemd-coredump[84285]: Resource limits disable core dumping for process 84283 (python3.9).
May 27 15:29:47 localhost.localdomain systemd-coredump[84285]: [🡕] Process 84283 (python3.9) of user 1000 dumped core.
May 27 15:29:47 localhost.localdomain systemd[1]: systemd-coredump@13-84284-0.service: Deactivated successfully.
```

Any Ideas?

**Comment by gjmulder** [comment] 2023-05-28 06:39
You're going to need to compare the AVX1 / AVX2 / AVX512* compilation options between the working build and the one throwing the illegal opcode.

If you're compiling in a VM, sometimes the virtualisation "lies" about what Intel extensions are available to the VM, when in fact they're only available on the host. Someone logged a ticket a while back where HyperV security settings was preventing the use of AVX512 by programs running in the VM.

**Comment by chen369** [comment] 2023-05-28 13:33
Gjmulder, that's interesting, why would it fail within the python binding VS from the vendor source? 

Do you know if when we build the python binding does it build the llama-cpp application with other cpu instructions that are hard-coded? 

There has to be something different from
Installing normally VS installing from source in llama-cpp-python.

Mind you llama-cpp works fine with cuBLAS it just doesn't work for me in llama-cpp-python.

**Comment by gjmulder** [comment] 2023-05-28 15:51
Maybe try building `llama-cpp-python` from source with the `--verbose` option? It will then pull in a specific commit of `llama.cpp.`

Next compare the output of a test programming using that uses the source build `llama-cpp-python` package with the output of `./main`. That ensures the _same_ `llama.cpp` commit is being used.

There's significant amount of change occurring in `llama.cpp` to the point where new features are being introduced faster than I can keep track of them. Best to assume nothing at this point. :man_shrugging:

**Comment by chen369** [comment] 2023-05-28 18:11
@gjmulder  I tried building with verbose and there isnt significan of value. 
I tried building with or with out ` -DLLAMA_AVX2=off` for fun both gave me the same result. 
However, after doing some more digging I think this issue opened on `llama-cpp` might be our issue. 

https://github.com/ggerganov/llama.cpp/issues/1583 


I suspect, that building "llama.cpp" directly works fine for me since I dident use `cmake` to build it. however since `llama-cpp-python` uses cmake and from what issue (https://github.com/ggerganov/llama.cpp/issues/1583) by default its building it with AVX2 built in is causing my compiled library to have support for instructions that are not supported. 

I think I would be able to replicate this issue directly on `llama.cpp` if I built it from source using `cmake`.

**Comment by chen369** [comment] 2023-05-28 18:33
@gjmulder and @vmajor 
Great news I was able to fix this issue.
It required me to modify /vendor/llama.cpp/CMakeLists.txt  In  the lines 56 and 70 I had to turn off `LLAMA_AVX2` and turn on `LLAMA_CUBLAS`  

Once that was done I was now able to build "llama-cpp-python" from source and install with pip natively and also import it in python no issues.


`(.venv) [ai00@localhost llama-cpp-python]$ python -c "from llama_cpp import *; print(llama_print_system_info())"
b'AVX = 1 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 0 | ARM_FMA = 0 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 | '1`


@vmajor I think if you were to do the same modification you should be able to build llama-cpp-python with the correct cpu instructions.

**Comment by vmajor** [comment] 2023-05-29 04:03
Thanks for the hard work. I can in fact run llama-cpp-python locally without any issue. It was just the docker image that would not run. I had not spent time trying to make a new docker image as I changed my workflow to use llama-cpp-python locally. There are many other toolchains that are more broken for me so I need to pick and choose what I focus on.

**Comment by gjmulder** [comment] 2023-05-29 07:01
> [ggerganov/llama.cpp#1583](https://github.com/ggerganov/llama.cpp/issues/1583)

I'm a Collaborator to `llama.cpp` so I labeled it with `build` + `bug` + `high priority`, given the `llama-cpp-python` dependency.

**Comment by gjmulder** [comment] 2023-07-10 06:46
CLosing please reopen if the problem is reproducible with the latest `llama-cpp-python` which includes an updated `llama.cpp`

**Closed by gjmulder** 2023-07-10 06:46 UTC
Labels: build, hardware

**Comment by decadance-dance** [comment] 2023-07-17 11:16
> CLosing please reopen if the problem is reproducible with the latest `llama-cpp-python` which includes an updated `llama.cpp`

What update are you referring to?
I upgraded to a new version of `llama-cpp-python` and still keep getting this error.
Maybe there are some flags or presets that I have to do when I install  `llama-cpp-python`?

**Comment by Mwni** [comment] 2023-08-02 05:02
@chen369's solution works, but for some environments, you may also have to set `LLAMA_FMA = off`.

**Comment by kkaarrss** [comment] 2023-08-05 18:59
I am running on old E5645 (Westmere) Xeons that do not support AVX at all. I can confirm that the below command works for me:

CMAKE_ARGS="-DLLAMA_CUBLAS=1 -DLLAMA_AVX=OFF -DLLAMA_AVX2=OFF -DLLAMA_F16C=OFF -DLLAMA_FMA=OFF" FORCE_CMAKE=1 pip install --upgrade --force-reinstall llama-cpp-python --no-cache-dir

So CMAKE_ARGS seems to work at this time. 

https://github.com/ggerganov/llama.cpp/issues/1027

**Comment by BobCN2017** [comment] 2023-08-30 11:31
> I am running on old E5645 (Westmere) Xeons that do not support AVX at all. I also ran into "Illegal instruction". But I can confirm that the below command works for me:
> 
> CMAKE_ARGS="-DLLAMA_CUBLAS=1 -DLLAMA_AVX=OFF -DLLAMA_AVX2=OFF -DLLAMA_F16C=OFF -DLLAMA_FMA=OFF" FORCE_CMAKE=1 pip install --upgrade --force-reinstall llama-cpp-python --no-cache-dir
> 
> Not a problem with CMAKE_ARGS.
> 
> [ggerganov/llama.cpp#1027](https://github.com/ggerganov/llama.cpp/issues/1027)

At first, I used this command to compile the wheel. However, after completion, when I tried to load the model, it returned None. I meticulously checked multiple times and noticed that its version had changed from 0.1.77 to 0.1.83. To address this, I specified the version by appending ==0.1.77 to the package name, recompiled, and reinstalled. After this adjustment, everything worked as expected. thanks.
