### ISSUE TITLE
Not work correctly with Llama-3

### ISSUE THREAD

**Issue by masterofaimoein** [abetlen/llama-cpp-python#1373] opened 2024-04-22 06:19 UTC
When I use llama-3 gguf file for create chat complation(my code):
        user_input = input("Hey dude")

        llm = Llama(
                model_path="/content/Meta-Llama-3-8B-Instruct.gguf",
                chat_format="llama-2",
                n_ctx = 512,
                n_batch = 512,
                n_gpu_layers = 32,
                verbose = True,
                
            )

        chat = llm.create_chat_completion(
            messages = [
                {
                    "role": "system", "content": "You name is Meta. You are helpful assistant."
                },

                {
                    "role": "user", "content": f"{user_input}"
                },

            ],

            temperature = 0.8,
            presence_penalty = 0.3,
            frequency_penalty = 0.5,
            top_k = 0.5,
            top_p = 0.5
        )

        output_generated = chat['choices'][0]['message']['content']

        return output_generated

I got this response(llama-3 not give main results like llama-2):
    - **Output**: `Hey! 👋 What can I help you with today? 🤔`

3.  `<s>[INST]You're a friendly AI assistant, and your responses should be polite and helpful(Use emoji in you sentences). User request is : Hi'   [/INST]`
    - **Output**: `Hi there! 😊 How are you doing today? I'm here to help with any questions or concerns you might have. 🤗`

4.  `<s>[INST]You're a sarcastic AI assistant, and your responses should be humorous and slightly ironic(Use emoji in you sentences). User request is : Hey'   [/INST]`
    - **Output**: `Oh joy, another user who wants to talk to me 😒. What's up? Need some advice or just want to waste my time with small talk? 🤔`

5.  `<s>[INST]You're a professional AI assistant, and your responses should be formal and informative(Use emoji in you sentences). User request is : Hi'   [/INST]`
    - **Output**: `Hello! 👋 I'm happy to assist you with any questions or concerns you may have. Please feel free to ask me anything, and I'll do my best to provide a helpful response. 📊`

These examples demonstrate how the `<s>` tag can be used to specify different personalities for the AI assistant, each with its own tone and style of communication.

**Note**: The `[/INST]` tag is used to indicate the end of the instruction block, which specifies the personality traits that should be applied in response to user input. This allows you to define multiple personality types within a single model or dialogue flow.

How can I solve that?

**Comment by xinge666** [comment] 2024-04-22 09:07
same question, caused by chatformat of llama3 ?  https://github.com/abetlen/llama-cpp-python/pull/1371

**Comment by masterofaimoein** [comment] 2024-04-22 13:19
> same question, caused by chatformat of llama3 ?  https://github.com/abetlen/llama-cpp-python/pull/1371

I think yes, llama-cpp-python needs to add llama3 chat format.

**Comment by masterofaimoein** [comment] 2024-04-22 15:50
> The chat format is wrong here. Also, it will not stop because the default <|end_of_text|> is never predicted by the instruct model. I have kept it changed to <|eot_id|>. I feel that <|end_of_text|> is for the base model.
> 
> This is Jan app which is using llama.cpp-python server through v1/chat/completion endpoint. The prompt format is working correctly by the server: ![image](https://private-user-images.githubusercontent.com/17230826/324510221-d85d9f85-d3b5-4dd4-8c4a-388ce980f567.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDEyODMsIm5iZiI6MTcxMzgwMDk4MywicGF0aCI6Ii8xNzIzMDgyNi8zMjQ1MTAyMjEtZDg1ZDlmODUtZDNiNS00ZGQ0LThjNGEtMzg4Y2U5ODBmNTY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDE1NDk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2YmRiNTUwN2E3MjJhMGQ0NTgyMjFkZDc5YWU4MWExYzI0YWQyNWZkODNlMmJlNzhmYjEzY2Q2YTI0YzNiNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TN2ziZZbR-zFfTsBRsdUoKNeTkh0ii4kxzS1oELHo20)

Thank you very much, I solved my problem with updating chat_format.py file. thanks for your answering

**Comment by andreabak** [comment] 2024-04-22 16:07
#1371 to add llama-3 chat format support is open and waiting for approval to merge. But before then, if you need to use llama-3 with llama-cpp-python right now, you could try out installing it from my forked branch with something like:
```sh
pip install 'llama-cpp-python @ git+https://github.com/andreabak/llama-cpp-python@dev-llama3_chat_format-abk16'
```

**Comment by masterofaimoein** [comment] 2024-04-22 17:12
> #1371 to add llama-3 chat format support is open and waiting for approval to merge. But before then, if you need to use llama-3 with llama-cpp-python right now, you could try out installing it from my forked branch with something like:
> ```sh
> pip install 'llama-cpp-python @ git+https://github.com/andreabak/llama-cpp-python@dev-llama3_chat_format-abk16'
> ```

Thank you su much.

How can I train Meta-llama-3-8B-Instruct-GGUF with our own dataset for our special tasks?

**Comment by andreabak** [comment] 2024-04-23 07:40
@masterofaimoein #1371 is merged so this is now solved in the main branch. This issue can be closed.

**Comment by masterofaimoein** [comment] 2024-04-23 10:16
> @masterofaimoein #1371 is merged so this is now solved in the main branch. This issue can be closed.

Thanks.

**Closed** 2024-04-23 10:17 UTC
