### ISSUE TITLE
Is it currently broken or what changed?

### ISSUE THREAD

**Issue by iactix** [abetlen/llama-cpp-python#439] opened 2023-06-30 16:56 UTC
I just updated to 28ec88c and now I am getting this when I run my stuff, even before loading a model:

```
Traceback (most recent call last):
  File "X:\MyStuff\server.py", line 14, in <module>
    from llama_cpp import Llama
  File "C:\Users\iactix\AppData\Local\Programs\Python\Python39\lib\site-packages\llama_cpp_python-0.1.67-py3.9-win-amd64.egg\llama_cpp\__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "C:\Users\iactix\AppData\Local\Programs\Python\Python39\lib\site-packages\llama_cpp_python-0.1.67-py3.9-win-amd64.egg\llama_cpp\llama_cpp.py", line 313, in <module>
    _lib.llama_load_model_from_file.argtypes = [c_char_p, llama_context_params]
  File "C:\Users\iactix\AppData\Local\Programs\Python\Python39\lib\ctypes\__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\iactix\AppData\Local\Programs\Python\Python39\lib\ctypes\__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'llama_load_model_from_file' not found
```

I am using windows and I compile llama-cpp-python myself and I updated it many times before. Compiling and installing didn't seem to be a problem. This is what I use for that, after uninstalling the previous version:

```
set CMAKE_ARGS=-DLLAMA_CUBLAS=on
set FORCE_CMAKE=1
python setup.py clean
python setup.py install
```

line 14 in my code is "from llama_cpp import Llama"

Edit: I am now using what I'm getting from pip install llama-cpp-python, which works fine with my code.

**Comment by crimsonskyfalling** [comment] 2023-07-02 16:25
I am also finding something broken when building/installing from source for cublas support as well. 

Previously, had this working at ~ v0.1.58 .  tried to move to latest and  so far unable to build/install @ v0.1.67, or v0.1.66 
currently trying to work my way back to a functional install with cublas support on WSL/Ubuntu... 

    from llama_cpp import Llama
ImportError: cannot import name 'Llama' from 'llama_cpp' (unknown location)

**Comment by crimsonskyfalling** [comment] 2023-07-02 16:58
I am able get the latest to install via pip install.   Finally, with cublas support on my cuda install i needed to use the following:

sudo CUDACXX=/usr/local/cuda-11.7/bin/nvcc CMAKE_ARGS="-DLLAMA_CUBLAS=on -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-11.7/" FORCE_CMAKE=1  pip install llama-cpp-python --force-reinst
all --upgrade --no-cache-dir


Still not sure why I can't pip install -e . from the local repo source however.

**Comment by gjmulder** [comment] 2023-07-10 06:59
Closing. Please reopen if the problem is reproducible with the latest `llama-cpp-python` which includes an updated `llama.cpp`

**Closed by gjmulder** 2023-07-10 06:59 UTC
Labels: bug, build
