### ISSUE TITLE
Cannot not seem to get blas = 1 working

### ISSUE THREAD

**Issue by darrinh** [abetlen/llama-cpp-python#502] opened 2023-07-19 07:51 UTC
Not sure what i'm missing, I've followed the steps to install with GPU support, however when  run a model I always see 'BLAS = 0' in the output:

`(test01) darrin01@chatbot01:~/Source/test01$ pip uninstall -y llama-cpp-python 
Found existing installation: llama-cpp-python 0.1.73

Uninstalling llama-cpp-python-0.1.73:

  Successfully uninstalled llama-cpp-python-0.1.73

(test01) darrin01@chatbot01:~/Source/test01$ CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python --no-cache-dir 
Collecting llama-cpp-python
  Downloading llama_cpp_python-0.1.73.tar.gz (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 6.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: typing-extensions>=4.5.0 in ./lib/python3.10/site-packages (from llama-cpp-python) (4.7.1)
Requirement already satisfied: numpy>=1.20.0 in ./lib/python3.10/site-packages (from llama-cpp-python) (1.25.1)
Requirement already satisfied: diskcache>=5.6.1 in ./lib/python3.10/site-packages (from llama-cpp-python) (5.6.1)
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml) ... done
  Created wheel for llama-cpp-python: filename=llama_cpp_python-0.1.73-cp310-cp310-linux_x86_64.whl size=265591 sha256=8cc0bf046203a3662c2719bbfe27a5992f1ab8347be04ca2d6b3c943d09b3a6c
  Stored in directory: /tmp/pip-ephem-wheel-cache-u7e78f0a/wheels/69/6a/cb/41fd7c0f7f77613d996b4981a3e9b345d2b416b016786956bc
Successfully built llama-cpp-python
Installing collected packages: llama-cpp-python
`

When I run an example script:

`llama.cpp: loading model from ./koala-7B.ggmlv3.q2_K.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 512
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 10 (mostly Q2_K)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.08 MB
llama_model_load_internal: mem required  = 4242.13 MB (+ 1026.00 MB per state)
llama_new_context_with_model: kv self size  =  256.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |`

any ideas?

thanks

**Comment by abetlen** [comment] 2023-07-19 20:10
Can you try reinstalling with the `--verbose` flag? This should tell you if cmake is able to locate the libraries correctly.

**Comment by darrinh** [comment] 2023-07-22 01:36
> Can you try reinstalling with the `--verbose` flag? This should tell you if cmake is able to locate the libraries correctly.

Thanks abetlen, that appears to be the issue. The toolkit is installed in /usr/local/cuda, I'll need to set the env. vars so it can find the toolkit.
```

  -- Found Threads: TRUE
  -- Unable to find cuda_runtime.h in "/usr/include" for CUDAToolkit_INCLUDE_DIR.
  -- Unable to find cublas_v2.h in either "" or "/math_libs/include"
  -- Unable to find cudart library.
  -- Could NOT find CUDAToolkit (missing: CUDAToolkit_INCLUDE_DIR CUDA_CUDART) (found version "12.2.91")
  CMake Warning at vendor/llama.cpp/CMakeLists.txt:292 (message):
    cuBLAS not found
```

**Comment by darrinh** [comment] 2023-07-22 02:23
In the end I had to do:

`CMAKE_ARGS="-DLLAMA_CUBLAS=on -DCUDA_PATH=/usr/local/cuda-12.2 -DCUDAToolkit_ROOT=/usr/local/cuda-12.2 -DCUDAToolkit_INCLUDE_DIR=/usr/local/cuda-12/include -DCUDAToolkit_LIBRARY_DIR=/usr/local/cuda-12.2/lib64"FORCE_CMAKE=1  pip install llama-cpp-python --no-cache-dir --verbose`

To get it to build.

**Comment by darrinh** [comment] 2023-07-22 02:25
but still seeing: "BLAS = 0"

**Comment by darrinh** [comment] 2023-07-22 02:39
yay "BLAS = 1" , had a dodgy symlink that when removed, allowed it to build properly.

Thanks

**Comment by leiserfg** [comment] 2023-07-24 19:09
I managed to build with clblast but when I run it the model just keeps loading forever without showing any log.

**Comment by gjmulder** [comment] 2023-07-30 07:15
Can you please close the issue if it is solved?

**Comment by leiserfg** [comment] 2023-07-30 07:18
My issue was caused by my distro shipping OneApi OpenCL when I don't have intel CPU/GPU which breaks OpenCL loading,  uninstalling it fixed the issue.

**Closed** 2023-07-30 07:39 UTC
Labels: build
