### ISSUE TITLE
Problems when i try to use this inside the default python 3.10 docker container

### ISSUE THREAD

**Issue by LLukas22** [abetlen/llama-cpp-python#70] opened 2023-04-11 14:19 UTC
When i try to install and use this package via a requirements file in the default 3.10 python container i get the following error when i try to import the module:
`Failed to load shared library '/usr/local/lib/python3.10/site-packages/llama_cpp/libllama.so': /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.29' not found (required by /usr/local/lib/python3.10/site-packages/llama_cpp/libllama.so)`

Am i doing something wrong? Or am i just missing some dependencies?

**Comment by abetlen** [comment] 2023-04-11 14:25
Do you mind posting the Dockerfile? I haven't tried to use this inside a container but I'l investigate.

**Comment by LLukas22** [comment] 2023-04-11 15:20
Alright i cant send you the Dockerfile, but i created a toy-example with your own server.

Dockerfile:
```
FROM python:3.10

#install
RUN pip3 install llama-cpp-python[server]

#Expose the ports
EXPOSE 8000

# Make a Dir for the models to be mounted into
RUN mkdir -p /var/lib/models

#Set environment 
ENV MODEL "/var/lib/models/ggjt-model.bin"

#Start server
CMD ["python3","-m","llama_cpp.server"]
```

I then started the container via this docker-compose file:
```
version: "3.9"
services:
 
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: llama-server
    container_name: llama-server

    ports:
      - "8000:8000"

    volumes:
      - [MODEL_DIR]:/var/lib/models
```

When running this the 'GLIBCXX_3.4.29' error is gone, but the model loads for a very long time and the container gets OOM killed sometimes. I'm running on 64GB so that's very strange. The other thing i noticed is that the container fails to bind the address but that's just docker IPv4 shenanigans. I will try to use llama-cpp-python[server] as a dependency in my other project and see  if it will get rid of the 'GLIBCXX_3.4.29' error.

**Comment by abetlen** [comment] 2023-04-11 15:28
So the GLIBC error is fixed now? I would also make sure the OOM issue isn't some Docker default limit.

**Comment by LLukas22** [comment] 2023-04-11 15:45
Thats the strange thing the dockerfile listed above works without any problems. But if im trying to run my Dockerfile im getting the "GLIBC" error.

This is my Dockerfile:

```
FROM python:3.10

RUN apt-get update -y
RUN apt-get install -y python3-pip graphviz-dev git gcc-4.9 
RUN apt-get upgrade -y libstdc++6 

#Expose the ports
EXPOSE 8001

# Copy Files
RUN mkdir -p /app
ADD ./ /app/
WORKDIR /app

# Install Requirements
RUN --mount=type=cache,target=/root/.cache/pip pip3 install -r ./api/requirements-cpu.txt

RUN --mount=type=cache,target=/root/.cache/pip pip3 install git+https://github.com/huggingface/transformers@a17841ac4945631e4e13c072fa2a329b98ebb8b6 

ENV PYTHONPATH "${PYTHONPATH}:/app"

#Build cache dir for transformers
ENV HF_HOME "/huggingface/cache"

CMD ["python3", "/app/api/main.py"]

```

and its using the following requirements file: 
```
protobuf==3.20.1
huggingface_hub
llama-cpp-python[server]
openai
pynvml
farm-haystack

#api dependencies
psutil
fastapi
uvicorn
dependency_injector
```

My guess is one of the dependencies in the requirements does some weird stuff, but i actually have no clue where to start looking.

**Comment by jmtatsch** [comment] 2023-04-12 00:30
I run within a Ubuntu container which works.
https://github.com/mkellerman/gpt4all-ui/ runs a 3.11 container and it works so I would guess the issue is not with llama-cpp-python but with your concrete dockerfile/requirements.
Especially I would try adding 
apt-get install -y build-essential

**Comment by LLukas22** [comment] 2023-04-12 07:04
I also played around a bit more and i couldnt get the container working, and i dont know why. All the other containers i build with llama-cpp-python work without any problems. I will probably host a seperate llama-cpp-python container and then use it via its REST api.

@abetlen Could we maybe get an official prebuild docker container for the REST server?

**Comment by abetlen** [comment] 2023-04-12 07:09
Yeah if someone wants to open a PR I can test / review it when I have some time.

**Comment by LLukas22** [comment] 2023-04-12 09:28
I could try later. But i guess i noticed another problem i had, when building my containers via github-actions and then trying to run them locally the containers exit with exitcode 132 hinting at an unsupported CPU instruction-set.  If build and run locally they work without any problems. 

My guess the is the llama.cpp dependencies are resolved in the build step of the container with the cpu feature flags of the github-actions-runner. Can i  define specific feature flags used for the llama.cpp compilation at setup time or should i look into first building llama.cpp manually and then setting it via the environment?

**Comment by abetlen** [comment] 2023-04-12 14:43
@LLukas22 that's definitely it, should check what llama.cpp does for this with their docker containers.

**Comment by LLukas22** [comment] 2023-04-12 16:27
@abetlen Yeah its pretty weird, i played around a bit but can't get it to work even if i use QEMU to force a linux/amd64 platform while building the image on an github-actions-runner. And i'm actually really confused what instruction set is missing as i'm using relatively new processors (AMD Zen  2 &  3) so avx and avx-2 are definitely there.

But i'm also no docker pro, so maybe i'm just missing something.

**Comment by abetlen** [comment] 2023-04-12 16:39
@LLukas22 is QEMU sufficient to emulate processor specific instruction sets? I'd imagine it's because of a mismatch between processor architectures in the github runner and your local machine.

**Comment by LLukas22** [comment] 2023-04-12 18:51
@abetlen Theoretically QEMU should be able to emulate any cpu features, but i dont know how it is implemented in docker build.
They probably create a vm with the cpu flags `host` or `max` which will use all features of the host system. Then the problem with the architecture mismatch happens when i try to run it locally. But i'm still a bit confused thought nearly all x64 cpus released in the last <5 years implement the same instructionsets 🤔

**Comment by abetlen** [comment] 2023-04-12 19:55
@LLukas22 https://github.com/ggerganov/llama.cpp/blob/master/.github/workflows/docker.yml describes how they build the llama.cpp docker image, not sure if you've checked that out

**Comment by LLukas22** [comment] 2023-04-13 07:59
@abetlen Yup i had a look and tried their image, it runs on my Intel machine but fails with exit code 132 on both my AMD based systems. I will create a new issue in the llama.cpp repository.

**Comment by gjmulder** [comment] 2023-04-13 08:16
These old build issues where `llama.cpp` gets confused in what features are exposed on different (virtualised?) h/w might be of help:

[Can it support avx cpu's older than 10 years old](https://github.com/ggerganov/llama.cpp/issues/451)
[better support for different x86_64 CPU instruction extensions](https://github.com/ggerganov/llama.cpp/issues/196)

**Comment by LLukas22** [comment] 2023-04-13 08:43
@gjmulder Well the images are build on an github-actions-runner which probably uses a virtualized Intel CPU. I then downloaded them an tried to run them on my AMD systems, which leads to the errors. The thing that confuses me is that all systems i used support all CPU features listed in the cmake file namely avx, avx2, fma and f16c. I don't quite get why an image build on one of these systems shouldn't work when moved to another system supporting the exact same instruction sets.

**Comment by gjmulder** [comment] 2023-04-13 09:25
I'm guessing here, as I haven't had time to repro, but will do so in the next few days:

Maybe do a `lscpu | grep Flags > /var/tmp/lscpu_build_flags` as part of github-actions-runner build and confirm that in fact they are the exactly same?

**Comment by LLukas22** [comment] 2023-04-13 18:41
@gjmulder Alright i ran it locally and on the github-actions-runner. Here are the results:

Actions Runner:
```
fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm avx512f avx512dq rdseed adx smap clflushopt avx512cd avx512bw avx512vl xsaveopt xsavec xsaves md_clear
```

Local:
```
fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl tsc_reliable nonstop_tsc cpuid extd_apicid pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext perfctr_core ssbd ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves clzero xsaveerptr arat npt nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload umip rdpid
```

Maybe the problem is  caused by the `avx512` instruction set?

**Comment by gjmulder** [comment] 2023-04-13 19:45
> Maybe the problem is caused by the `avx512` instruction set?
@LLukas22 this might be relevant: https://github.com/ggerganov/llama.cpp/pull/809

**Comment by LLukas22** [comment] 2023-04-14 07:52
@gjmulder  Yes this is probably related. Do you know if it is possible to somehow change what featuresets are used in the compilation of llama.cpp via environment variables? Then i could just set them in the dockerfile and use the normal setup from this repo. If not i probably have to build it manually and then copy around the binary.

**Comment by gjmulder** [comment] 2023-04-14 08:10
@LLukas22 I seem to remember that the Makefile was checking the output of `lscpu`, but it seems things have moved on since then.

[This](https://stackoverflow.com/questions/28939652/how-to-detect-sse-sse2-avx-avx2-avx-512-avx-128-fma-kcvi-availability-at-compile) might help. Maybe you can [override the `g++` generated macros](https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html)? A bit hacky, but might work :crossed_fingers:

**Comment by LLukas22** [comment] 2023-04-14 09:40
@gjmulder Hm this could actually work im gonna try it later and i will just try to disable `avx512` but i dont know what flag to set 😓. But i guess i also have to set the `CFLAGS` as ggml is compiled with them.

**Comment by LLukas22** [comment] 2023-04-15 11:33
@gjmulder Alrigth i had another look, setting the `CXXFLAGS` or `CFLAGS` is not possible as they are reset in the make file. But if i use cmake i can simply pass an `-D LLAMA_AVX512=OFF` flag to enable/disable the `avx512` instructions. I will probably use this to build llama.cpp manually in a workflow and then copy the resulting `libllama.so` into my docker containers. This way i can easily create a separate `avx512` and `avx2` container.

**Comment by gjmulder** [comment] 2023-04-15 11:36
Push them to Docker hub when you're done? My AMD is pre-`axv512`

**Comment by LLukas22** [comment] 2023-04-17 09:12
@abetlen Alright i now have an action that builds me a `libllama.so` binary with and without `avx512`. But if i copy this binary into my docker container and set the `LLAMA_CPP_LIB` environment variable to point towards the binary i'm back to the `'GLIBCXX_3.4.29' not found` error 🤔.

The my dockerfile now looks like this and is available in [this](https://github.com/LLukas22/llama-cpp-python) fork:
```
FROM python:3.10

#Copy the compiled llama.so file to the container
COPY ./lib /lib/

#Set the environment variable for the llama.so file
ENV LLAMA_CPP_LIB /lib/llama.so

# Copy the python code to the container
RUN mkdir -p /app
COPY ./llama_cpp /app
WORKDIR /app

#Add the current directory to the PYTHONPATH
ENV PYTHONPATH "${PYTHONPATH}:/app"

# Install Requirements
RUN --mount=type=cache,target=/root/.cache/pip pip3 install -r ./server/requirements.txt

#Set default environment variables
ENV HOST 0.0.0.0
ENV PORT 8000

#Expose the port
EXPOSE ${PORT}

#Run the server
CMD ["python3","-m","server"]
``` 
This is the binary i used: [llama.zip](https://github.com/abetlen/llama-cpp-python/files/11248297/llama.zip)

I'm at my wits ends here, i'm probably just gonna build my containers on the machines i will run them on.


<img src="https://media.tenor.com/lxqihLckfJcAAAAM/this-is-fine.gif" width="250" height="250" />

**Comment by gjmulder** [comment] 2023-04-17 11:39
Here's to help you debug @LLukas22 :smile: 

```
$ docker build --force-rm -t lcp .
Sending build context to Docker daemon  7.065MB
Step 1/12 : FROM python:3.10
 ---> c339f65d6ddf
Step 2/12 : COPY ./lib /lib/
COPY failed: file not found in build context or excluded by .dockerignore: stat lib: file does not exist

$ find -name lib | wc -l
0
```

**Comment by LLukas22** [comment] 2023-04-17 12:07
@gjmulder Alright thats kind of my bad, the `lib` folder is created in a github action and contains the `llama.so` binary i added above. I now also added a `lib` folder with an `llama.so` that was generated this way into the repo for testing purposes. 

There is no need to build or recursively checkout the repo. To reproduce the issue i'm experiencing just clone the fork and run a docker build and run on the dockerfile. The build should work without any errors and when trying to run the container the `'GLIBCXX_3.4.29' not found` error should occure.

The buildprocess of the `llama.so` binary is described in [this](https://github.com/LLukas22/llama-cpp-python/blob/main/.github/workflows/build-and-release-docker.yml) workflow file.

**Closed** 2023-05-02 05:06 UTC
