### ISSUE TITLE
[ubuntu] [1080ti] CUDA error 3 at .. ggml-cuda.cu:2268: initialization error

### ISSUE THREAD

**Issue by andzejsp** [abetlen/llama-cpp-python#382] opened 2023-06-16 07:27 UTC
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [ ] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [ ] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ ] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

To work with my VM linux ubuntu GTX1080ti GPU passthrough, some old binding version few weks ago was working with GPU (manually installed) but now 0.1.63 is not. 

It works on my windows machine RTX3090 no problem.

# Current Behavior

Im using this binding via https://github.com/ParisNeo/lollms-webui 
Load binding, load model, get error

```
 ******************* Building Binding from main Process *************************
Loading binding llama_cpp_official install ON
-------------- llama_cpp_official binding -------------------------------
This is the first time you are using this binding.
Collecting llama-cpp-python (from -r /home/sd2/gpt4all-ui-andzejsp/env/lib/python3.10/site-packages/lollms/bindings_zoo/llama_cpp_official/requirements.txt (line 1))
  Downloading llama_cpp_python-0.1.63.tar.gz (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 36.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting llamacpp (from -r /home/sd2/gpt4all-ui-andzejsp/env/lib/python3.10/site-packages/lollms/bindings_zoo/llama_cpp_official/requirements.txt (line 2))
  Downloading llamacpp-0.1.14-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (243 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 243.4/243.4 kB 413.3 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=4.5.0 in ./env/lib/python3.10/site-packages (from llama-cpp-python->-r /home/sd2/gpt4all-ui-andzejsp/env/lib/python3.10/site-packages/lollms/bindings_zoo/llama_cpp_official/requirements.txt (line 1)) (4.6.3)
Requirement already satisfied: numpy>=1.20.0 in ./env/lib/python3.10/site-packages (from llama-cpp-python->-r /home/sd2/gpt4all-ui-andzejsp/env/lib/python3.10/site-packages/lollms/bindings_zoo/llama_cpp_official/requirements.txt (line 1)) (1.24.3)
Collecting diskcache>=5.6.1 (from llama-cpp-python->-r /home/sd2/gpt4all-ui-andzejsp/env/lib/python3.10/site-packages/lollms/bindings_zoo/llama_cpp_official/requirements.txt (line 1))
  Downloading diskcache-5.6.1-py3-none-any.whl (45 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.6/45.6 kB 311.6 MB/s eta 0:00:00
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml) ... done
  Created wheel for llama-cpp-python: filename=llama_cpp_python-0.1.63-cp310-cp310-linux_x86_64.whl size=344998 sha256=09ec04e3ab9e2ebac120ad6fa2302bb7258f6dc2d781cea4b6291a58892c5c3e
  Stored in directory: /tmp/pip-ephem-wheel-cache-4pq9u4na/wheels/68/c9/cb/ebc9d1bf7e7651737b43dcf027d408f21465c5fea38aa306ed
Successfully built llama-cpp-python
Installing collected packages: llamacpp, diskcache, llama-cpp-python
Successfully installed diskcache-5.6.1 llama-cpp-python-0.1.63 llamacpp-0.1.14
Installed successfully
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce GTX 1080 Ti
Binding loaded successfully
 ******************* Building mounted Personalities from main Process *************************
* english/generic/lollms
Loading from /home/sd2/gpt4all-ui-andzejsp/env/lib/python3.10/site-packages/lollms/personalities_zoo/english/generic/lollms
selected : 0
 ************ Personalities mounted (Main process) ***************************
Checking discussions database... ok
 ******************* Building Binding from generation Process *************************
Loading binding llama_cpp_official install ON
Binding loaded successfully
Loading model : /home/sd2/gpt4all-ui-andzejsp/models/llama_cpp_official/baize-v2-13b.ggmlv3.q4_0.bin
llama.cpp: loading model from /home/sd2/gpt4all-ui-andzejsp/models/llama_cpp_official/baize-v2-13b.ggmlv3.q4_0.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =    0.09 MB
WARNING: failed to allocate 0.09 MB of pinned memory: initialization error
llama_model_load_internal: using CUDA for GPU acceleration
llama_model_load_internal: mem required  = 5627.80 MB (+ 1608.00 MB per state)
llama_model_load_internal: allocating batch_size x 1 MB = 512 MB VRAM for the scratch buffer
llama_model_load_internal: offloading 20 repeating layers to GPU
llama_model_load_internal: offloaded 20/43 layers to GPU
llama_model_load_internal: total VRAM used: 3916 MB
Please open your browser and go to http://0.0.0.0:9600 to view the ui
debug mode:false
...................................................CUDA error 3 at /tmp/pip-install-jwx8ttxm/llama-cpp-python_d1fa921b54e942bab84294b2d6c7e011/vendor/llama.cpp/ggml-cuda.cu:2268: initialization error
Client eshyddBljK-YW35tAAAB connected
- Loading discussion
    Recovered json data
    Discussion id :1

```

I tried `pip install llama-cpp-python --force-reinstall --upgrade --no-cache-dir` but it dont recognize my GPU, atleast it  dont show in console 

What else can i try? Im no pythonist, so please help me

**Comment by andzejsp** [comment] 2023-06-16 11:07
another thing i noticed that i have cuda 11.5, while windows is working with 11.7

```
sd2@sd2:~/gpt4all-ui-andzejsp$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0
```

**Comment by andzejsp** [comment] 2023-06-16 12:33
more progress
i installed cude as per guide, wanted to get 11.7 but it installed 12.1
https://developer.nvidia.com/cuda-11-7-0-download-archive?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=22.04&target_type=deb_network

```
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin
```
```
sudo mv cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600
```
```
sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/3bf863cc.pub
```
```
sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/ /"
```
```
sudo apt-get update
```
```
sudo apt-get -y install cuda
```

And after reboot i lost `nvcc`

```bash
sd2@sd2:~/gpt4all-ui-andzejsp$ nvcc
Command 'nvcc' not found, but can be installed with:
sudo apt install nvidia-cuda-toolkit
sd2@sd2:~/gpt4all-ui-andzejsp$ sudo apt install nvidia-cuda-toolkit
[sudo] password for sd2: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libcuinj64-11.5 : Depends: libnvidia-compute-495 (>= 495) but it is not going to be installed or
                            libnvidia-compute-495-server (>= 495) but it is not installable or
                            libcuda.so.1 (>= 495) or
                            libcuda-11.5-1
 libnvidia-ml-dev : Depends: libnvidia-compute-495 (>= 495) but it is not going to be installed or
                             libnvidia-compute-495-server (>= 495) but it is not installable or
                             libnvidia-ml.so.1 (>= 495)
 nvidia-cuda-dev : Depends: libnvidia-compute-495 (>= 495) but it is not going to be installed or
                            libnvidia-compute-495-server (>= 495) but it is not installable or
                            libcuda.so.1 (>= 495) or
                            libcuda-11.5-1
                   Recommends: libnvcuvid1 but it is not installable
E: Unable to correct problems, you have held broken packages.
sd2@sd2:~/gpt4all-ui-andzejsp$ 

```
But good news is that binding is working:

```bash
Upgrading configuration... ******************* Building Binding from generation Process *************************
Loading binding llama_cpp_official install ON
Binding loaded successfully
Loading model : /home/sd2/gpt4all-ui-andzejsp/models/llama_cpp_official/airoboros-13b-gpt4.ggmlv3.q4_0.bin
llama.cpp: loading model from /home/sd2/gpt4all-ui-andzejsp/models/llama_cpp_official/airoboros-13b-gpt4.ggmlv3.q4_0.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =    0.09 MB
llama_model_load_internal: using CUDA for GPU acceleration
llama_model_load_internal: mem required  = 5627.80 MB (+ 1608.00 MB per state)
llama_model_load_internal: allocating batch_size x 1 MB = 512 MB VRAM for the scratch buffer
llama_model_load_internal: offloading 20 repeating layers to GPU
llama_model_load_internal: offloaded 20/43 layers to GPU
llama_model_load_internal: total VRAM used: 3916 MB
....................................................................................................
llama_init_from_file: kv self size  = 1600.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 | 
Model created successfully

OK
Starting message generation bylollms
Received message : are cats dogs?
Generating message...
llama_tokenize: too many tokens
Cats are cats are cats are cats are cats are cats are cats are cats are cats are cats are cats are cats are cats are cats are cats are cats are cats are cats are cats are cats are cats are cats are cats are cats are cats are cats are cats are cats are cats are cats are cats are cCanel request received
Stop generation received
Finished executing the generation
atsGeneration canceled
Canel request received
Stop generation received

## Done Generation ##


## Done ##


```

```
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1035      G   /usr/lib/xorg/Xorg                            4MiB |
|    0   N/A  N/A      2538      C   python                                      250MiB |
|    0   N/A  N/A      2539      C   python                                     5858MiB |
+---------------------------------------------------------------------------------------+
Fri Jun 16 15:20:07 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1080 Ti      On | 00000000:00:10.0 Off |                  N/A |
| 30%   51C    P2               77W / 320W|   6122MiB / 11264MiB |     22%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
```

**Comment by gjmulder** [comment] 2023-07-10 07:02
Closing. Please reopen if the problem is reproducible with the latest `llama-cpp-python` which includes an updated `llama.cpp`

**Closed by gjmulder** 2023-07-10 07:02 UTC
Labels: build, llama.cpp
