### ISSUE TITLE
Can't set n_gqa with server

### ISSUE THREAD

**Issue by rodrigo-pedro** [abetlen/llama-cpp-python#528] opened 2023-07-26 00:19 UTC
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

Being able to run the server with --n_gqa 8

# Current Behavior

```
 warnings.warn(
usage: __main__.py [-h] [--model MODEL]
                   [--model_alias MODEL_ALIAS] [--n_ctx N_CTX]
                   [--n_gpu_layers N_GPU_LAYERS]
                   [--tensor_split TENSOR_SPLIT]
                   [--rope_freq_base ROPE_FREQ_BASE]
                   [--rope_freq_scale ROPE_FREQ_SCALE]
                   [--seed SEED] [--n_batch N_BATCH]
                   [--n_threads N_THREADS] [--f16_kv F16_KV]
                   [--use_mlock USE_MLOCK] [--use_mmap USE_MMAP]
                   [--embedding EMBEDDING] [--low_vram LOW_VRAM]
                   [--last_n_tokens_size LAST_N_TOKENS_SIZE]
                   [--logits_all LOGITS_ALL] [--cache CACHE]
                   [--cache_type CACHE_TYPE]
                   [--cache_size CACHE_SIZE]
                   [--vocab_only VOCAB_ONLY] [--verbose VERBOSE]
                   [--host HOST] [--port PORT]
                   [--interrupt_requests INTERRUPT_REQUESTS]
                   [--n_gqa N_GQA] [--rms_norm_eps RMS_NORM_EPS]
__main__.py: error: argument --n_gqa: invalid Optional value: '8'
```

**Comment by skrbnv** [comment] 2023-07-27 07:01
There's an issue with how __main__.py processes argument type, it can't deal with Optional[int]
As a quick fix you can locate where package is stored and change Optional[int] to int

It's in app.py, Settings
`    n_gqa: Optional[int] = Field(
        default=None,
        description="TEMPORARY: Set to 8 for Llama2 70B",
    )`

**Comment by saisamarthtaluri** [comment] 2023-07-28 10:12
Can confirm that by changing it to: 

` n_gqa: int = Field( default=None, description="TEMPORARY: Set to 8 for Llama2 70B", )`

works

**Comment by maxchen-000** [comment] 2023-07-28 13:58
you can also set the environment variable:
`export N_GQA=8`

**Comment by abetlen** [comment] 2023-07-28 18:41
@saisamarthtaluri @skrbnv thank you for pointing this out, I'll push the fix shortly!

**Comment by gjmulder** [comment] 2023-07-30 07:06
Duplicate of #524

**Comment by jasoncaojingren** [comment] 2023-08-04 05:05
In the file "llama_cpp/server/app.py", if change it to 

    n_gqa: Union[int, None] = Field(

will work. Anyone could make a change?

**Comment by gaby** [comment] 2023-09-03 05:02
@gjmulder @abetlen Any updates on this? I can't get `LlaMA2-7b` to work. It may be related to this.

```console
lama.cpp: loading model from /usr/src/app/weights/Facebook-LLaMA2-7B.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 512
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_head_kv  = 4
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: n_gqa      = 8
llama_model_load_internal: rnorm_eps  = 5.0e-06
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.08 MB
error loading model: llama.cpp: tensor 'layers.0.attention.wk.weight' has wrong shape; expected  4096 x   512, got  4096 x  4096
```

**Comment by abetlen** [comment] 2023-09-14 04:54
With the transition to gguf the n_gqa value is set automatically and has been removed from the llama.cpp api so I'll close this issue.

**Closed by abetlen** 2023-09-14 04:54 UTC
Labels: bug, llama.cpp
