### ISSUE TITLE
Distribute wheels with cuBLAS support for all supported NVIDIA GPU architectures

### ISSUE THREAD

**Issue by jllllll** [abetlen/llama-cpp-python#400] opened 2023-06-19 19:23 UTC
I recently discovered that llama-cpp-python can be compiled with cuBLAS support for all supported GPU architectures by setting the `CUDAFLAGS` environment variable to `-arch=all`. On Windows, I can use these commands in CMD:
```cmd
set FORCE_CMAKE=1
set "CMAKE_ARGS=-DLLAMA_CUBLAS=on"
set "CUDAFLAGS=-arch=all -lcublas"
python -m pip install git+https://github.com/abetlen/llama-cpp-python
```
Note that, due to an issue with the current llama.cpp version in this repo, `-lcublas` has to be added as well in order to link the needed cuBLAS library. Setting the `VERBOSE` environment variable to `1` allows you to see the full output of the build process. Doing this, I can see that it is indeed building for all architectures as it shows a warning about the deprecated Kepler architectures.

The resulting wheel works on my own system, but that is to be expected. I have not been able to test if a wheel works on a different system.

This will greatly improve the user experience for text-generation-webui. Especially for Windows users due to eliminating the need for Visual Studio.

**Comment by jllllll** [comment] 2023-06-19 19:47
Seems this method does not work with the latest llama.cpp due to them changing their CMakeLists.txt to use `-arch=native`.

**Comment by gjmulder** [comment] 2023-06-20 06:12
Duplicate of #243

**Closed** 2023-06-20 07:06 UTC
Labels: duplicate, enhancement, build, hardware
