### ISSUE TITLE
Error: Attempt to split tensors that exceed maximum supported devices. Current LLAMA_MAX_DEVICES=1

### ISSUE THREAD

**Issue by irthomasthomas** [abetlen/llama-cpp-python#1166] opened 2024-02-07 13:03 UTC
Hey, I'm not sure if this is a bug, or I just need change a config somewhere, but since the update, I get this error when I try to run models split across two cuda devices:

`ValueError: Attempt to split tensors that exceed maximum supported devices. Current LLAMA_MAX_DEVICES=1`

Is that related to this? https://github.com/ggerganov/llama.cpp/pull/5240

Here is the command I ran:
`python3 -m llama_cpp.server --model /Models/deepseek-coder-33b-instruct.Q4_K_M.gguf --n_gpu_layers 56 --tensor_split 64 36 --offload_kqv false --n_ctx 8000 --n_batch 56 --chat_format chatml`

**Comment by hamza233** [comment] 2024-02-07 22:01
Getting same error...

**Comment by bani6809** [comment] 2024-02-12 03:19
same error here. I have 4 x 3090 and it won't let me use them.

**Comment by abetlen** [comment] 2024-02-12 09:41
Hey sorry for the late reply, this shouldn't be related to that issue as I'd already migrated to using the `llama_max_devices` function. Can you try running `python3 -c "import llama_cpp; print(llama_cpp.llama_max_devices())"`?

**Comment by bani6809** [comment] 2024-02-19 05:24
```
admin@llm:~/models$ python3 -c "import llama_cpp; print(llama_cpp.llama_max_devices())"
1
```

**Comment by abetlen** [comment] 2024-02-22 04:38
Looking into it a bit these are certainly caused by the library not building with **any** gpu support, 

```c
size_t llama_max_devices(void) {
#if defined(GGML_USE_METAL)
    return 1;
#elif defined(GGML_USE_CUBLAS)
    return GGML_CUDA_MAX_DEVICES;
#elif defined(GGML_USE_SYCL)
    return GGML_SYCL_MAX_DEVICES;
#elif defined(GGML_USE_VULKAN)
    return GGML_VK_MAX_DEVICES;
#else
    return 1;
#endif
}
```

`llama_max_devices` just returns the value of `GGML_CUDA_MAX_DEVICES` which should be 16 if you successfully compiled with CUBLAS. I would reinstall with the build flags from the README and if that's still not working post your build log `CMAKE_ARGS="..." pip install llama-cpp-python --verbose`

**Comment by thiner** [comment] 2024-02-22 08:44
in `llama_cpp.py`, below code fails everytime. it's still referencing LLAMA_MAX_DEVICES, rather than function `llama_max_devices()`. Is this the root cause?
```python
 if self.tensor_split is not None:
            if len(self.tensor_split) > llama_cpp.LLAMA_MAX_DEVICES:
                raise ValueError(
                    f"Attempt to split tensors that exceed maximum supported devices. Current LLAMA_MAX_DEVICES={llama_cpp.LLAMA_MAX_DEVICES}"
                )
```

**Comment by cebtenzzre** [comment] 2024-02-22 20:47
> in `llama_cpp.py`, below code fails everytime. it's still referencing LLAMA_MAX_DEVICES, rather than function `llama_max_devices()`. Is this the root cause?

No, LLAMA_MAX_DEVICES comes from a call to llama_max_devices:
https://github.com/abetlen/llama-cpp-python/blob/eb56ce2e2ab2007616905c64d93aa456b8149065/llama_cpp/llama_cpp.py#L124

You have most likely built llama-cpp-python without GPU support.

**Comment by thiner** [comment] 2024-02-23 05:45
Interesting, I built my docker container from code, the key step is 
`RUN CUDACXX=/usr/local/cuda-12/bin/nvcc CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip3 install -e .[server]`
with the built-out container, I encountered the LLAMA_MAX_DEVICES = 1 issue.

I modified this line this morning, change it to `RUN CUDACXX=/usr/local/cuda-12/bin/nvcc CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip3 install -e .`, it works!

**Comment by abetlen** [comment] 2024-02-26 17:32
Closing for now, will reopen if someone has an issue where max devices is 1 with a GPU enabled installation.

**Closed by abetlen** 2024-02-26 17:32 UTC
Labels: bug

**Comment by LiberiFatali** [comment] 2024-06-11 07:04
I have just got this error with version 0.2.78.
Previous versions (.77, .76, .75) worked fine.

**Comment by camomiy** [comment] 2024-07-24 08:31
At the office we're having the same issue.

At first, manually building didn't work so we moved to the WHL prebuilt. Which worker for version `0.2.81`
But now, with latest prebuilt package, it doesn't work anymore.


`pip install llama-cpp-python==0.2.81   --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu124 --upgrade --force-reinstall`

Later we run the following commands : 

```txt
python -c "import llama_cpp; print(llama_cpp.llama_max_devices())"
16
python -c "import llama_cpp; print(llama_cpp.llama_supports_gpu_offload())"
True
```

And we can see GPU support works.

Later on with latest prebuilt wheel (and even the manual built one) :  

`pip install llama-cpp-python   --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu122 --upgrade`


```txt
python -c "import llama_cpp; print(llama_cpp.llama_max_devices())"
1
python -c "import llama_cpp; print(llama_cpp.llama_supports_gpu_offload())"
False
```

Now we can see GPU support is "dead". Only from this version and above.

**Comment by camomiy** [comment] 2024-07-24 08:47
And of course, tensor split and GPU supports works with no issue on llama.cpp binary (HEAD, master).

**Comment by freckletonj** [comment] 2024-08-17 21:25
This is still a problem, and all instructions fail with a llama 3.1 gguf:

```sh
# 1
pip install llama-cpp-python \
  --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu122

# 2
CMAKE_ARGS="-DGGML_CUDA=on" pip install llama-cpp-python

# 3
git clone ...
CMAKE_ARGS="-DGGML_CUDA=on" pip install -e ../lib/llama-cpp-python/ --verbose

# 4
LLAMA_MAX_DEVICES=2 my_thing  # it never even hears the ENV VAR (!?), still reports as 1 device
```

**Comment by freckletonj** [comment] 2024-08-17 21:51
@abetlen I've tried all available GPU installs, and I'm failing to install or build for using 2 GPUs on llama 3.1 70B gguf ^^^
(re: https://github.com/abetlen/llama-cpp-python/issues/1166#issuecomment-1964717272)

**Comment by freckletonj** [comment] 2024-10-27 22:40
Just tried again now weeks later and this **worked**:

```sh
CMAKE_ARGS="-DGGML_CUDA=on" pip install llama-cpp-python --force-reinstall --no-cache-dir
```
